### ISSUE TITLE
Videos imbedded in iframes do not display

### ISSUE THREAD

**Issue by levybee** [uncatcrea/wpak-off-canvas-themes#14]
Hi, 
     Thank you for the great work. I have an issue regarding embedded videos using iframes, they do not show on the app. 

I tried editing prepare-content.php and removed this part:

`foreach($iframeCollection as $iframe) {
        $iframe->setAttribute('data-src',$iframe->getAttribute('src'));
        $iframe->setAttribute('src','');
    }`

and  functions.js

`// Remove all iframes to get a smooth closing transition (notably because of YouTube iframes)
            //$('#' + currentContainerId + ' ' + 'iframe').remove();
`

and

` // We defer video loading to keep transitions smooth
            //loadAndFormatVideosFor( currentScreenObject ); `

but I still have the same problem. However when I embed the iframe code directly into single.html template the video gets displayed. Could there be a script that strips the iframe tags?

Thank you,

Levy

**Comment by blupu** [comment]
Hi Levy, thank for using WP-AppKit and Q themes. Could you copy/paste the iframe code you're trying to embed?

**Comment by blupu** [comment]
One thing though, I assume you're using the new Q Themes instead of the old Canvas themes, aren't you?

**Comment by levybee** [comment]
Yes I am using the new Q Themes. Below is the iframe code:

`<iframe src="https://www.youtube.com/embed/gHkKD6UtsYg" width="400" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>`

**Comment by blupu** [comment]
Hi @levybee I have re-opened your issue in the Q for Android repo as this repo is deprecated: https://github.com/uncatcrea/q-android/issues/5.
